version: '3'
services:
  flask:
    build: .
    restart: always
    networks:
      - postgres_network
      - flask_network
      - react_network
    links:
      - postgres
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_URI=postgresql://vettery:vettery@postgres:5432/vettery
    volumes: ['.:/vetteryQ']
    command: make run

  react:
    build: vqf/.
    restart: always
    stdin_open: true
    networks:
      - flask_network
      - react_network
    links:
      - flask
    depends_on:
      - flask
    ports:
      - "3000:3000"
      - "8000"

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST=data
      - POSTGRES_USER=vettery
      - POSTGRES_PASSWORD=vettery
      - POSTGRES_DB=vettery
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    networks:
      - postgres_network

volumes:
  postgres_volume:

networks:
  postgres_network:
    driver: bridge
  flask_network:
    driver: bridge
  react_network:
    driver: bridge
