version: '3'
services:
  flask:
    build: .
    restart: always
    networks:
#      - nginx_network
      - postgres_network
#      - redis_network
    links:
      - postgres
#      - redis
    depends_on:
      - postgres
#      - redis
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_URI=postgresql://vettery:vettery@postgres:5432/vettery
    command: make run

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST=data
      - POSTGRES_USER=vettery
      - POSTGRES_PASSWORD=vettery
      - POSTGRES_DB=vettery
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    networks:
      - postgres_network
#
#  redis:
#    restart: always
#    image: redis:latest
#    ports:
#      - "6379:6379"
#    volumes:
#      - redis_volume:/data
#    networks:
#      - redis_network
#
#  nginx:
#    image: nginx:1.13
#    ports:
#      - "8000:80"
#    volumes:
#      - ./nginx/conf.d:/etc/nginx/conf.d
#      - static_volume:/django/static
#      - media_volume:/django/media
#    networks:
#      - nginx_network
#    depends_on:
#      - django
#
volumes:
  postgres_volume:
#  static_volume:
#  media_volume:
#  redis_volume:
#
networks:
  postgres_network:
    driver: bridge
#  redis_network:
#    driver: bridge
#  nginx_network:
#    driver: bridge
